services:
  faqs:
    build: .
    restart: always
    pull_policy: build
    volumes:
      - data:/data
    environment:
      - ADMIN_SECRET=${ADMIN_SECRET}
      - PATH_PREFIX=/faqs

volumes:
  data:
